@startuml
enum UTILMD9013 {
    E01,
    E02,
    E03,
    E05,
    E06,
    E11,
    E15,
    E17,
    Z01,
    Z09,
    Z15,
    Z26,
    Z29,
    Z33,
    Z37,
    Z38,
    Z39,
    Z40,
    Z41,
    Z44,
    Z69,
    ZB2,
    ZB3,
    ZB6,
    ZC6,
    ZC7,
    ZC8,
    ZG9,
    ZH0,
    ZH1,
    ZH2,
    ZD0,
    ZD9,
    ZE3,
    ZE4,
    ZE5,
    ZE6,
    ZE7,
    ZE8,
    ZE9,
    ZF0,
    ZF1,
    ZF2,
    ZF3,
    ZF4,
    ZF5,
    ZF6,
    ZF7,
    ZF8,
    ZG5,
    ZG6,
    ZG7,
    ZG8,
    ZI8,
    ZI9,
    ZJ0,
    ZJ1,
    ZJ4,
}
@enduml
