version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "00:37"
    reviewers:
      - "Hochfrequenz/BO4E-dotnet"
    ignore:
      - dependency-name: "System.Text.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.Logging.*"
        update-types: ["version-update:semver-major"]
