version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "System.Text.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.Logging.*"
        update-types: ["version-update:semver-major"]
     groups:
       mstest:
        applies-to: version-updates
        patterns:
          - "MSTest.*"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
