version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@Hochfrequenz/c-developers-review-team"
    ignore:
      - dependency-name: "System.Text.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.Logging.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "System.Text.Json"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
