@startuml
class LenientParsingExtensions <<static>> {
    + {static} GetJsonSerializerSettings(lenient:LenientParsing) : JsonSerializerSettings
    + {static} GetJsonSerializerSettings(lenient:LenientParsing, userPropertiesWhiteList:HashSet<string>) : JsonSerializerSettings
}
@enduml
