@startuml
enum BDEWArtikelnummer {
    LEISTUNG,
    LEISTUNG_PAUSCHAL,
    GRUNDPREIS,
    REGELENERGIE_ARBEIT,
    REGELENERGIE_LEISTUNG,
    NOTSTROMLIEFERUNG_ARBEIT,
    NOTSTROMLIEFERUNG_LEISTUNG,
    RESERVENETZKAPAZITAET,
    RESERVELEISTUNG,
    ZUSAETZLICHE_ABLESUNG,
    PRUEFGEBUEHREN_AUSSERPLANMAESSIG,
    WIRKARBEIT,
    SINGULAER_GENUTZTE_BETRIEBSMITTEL,
    ABGABE_KWKG,
    ABSCHLAG,
    KONZESSIONSABGABE,
    ENTGELT_FERNAUSLESUNG,
    UNTERMESSUNG,
    BLINDMEHRARBEIT,
    ENTGELT_ABRECHNUNG,
    SPERRKOSTEN,
    ENTSPERRKOSTEN,
    MAHNKOSTEN,
    MEHR_MINDERMENGEN,
    INKASSOKOSTEN,
    BLINDMEHRLEISTUNG,
    ENTGELT_MESSUNG_ABLESUNG,
    ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK,
    AUSGLEICHSENERGIE,
    ZAEHLEINRICHTUNG,
    WANDLER_MENGENUMWERTER,
    KOMMUNIKATIONSEINRICHTUNG,
    TECHNISCHE_STEUEREINRICHTUNG,
    PARAGRAF_19_STROM_NEV_UMLAGE,
    BEFESTIGUNGSEINRICHTUNG,
    OFFSHORE_HAFTUNGSUMLAGE,
    FIXE_ARBEITSENTGELTKOMPONENTE,
    FIXE_LEISTUNGSENTGELTKOMPONENTE,
    UMLAGE_ABSCHALTBARE_LASTEN,
    MEHRMENGE,
    MINDERMENGE,
    ENERGIESTEUER,
    SMARTMETER_GATEWAY,
    STEUERBOX,
    MSB_INKL_MESSUNG,
}
@enduml
