@startuml
enum BoTyp {
    ANSPRECHPARTNER,
    ENERGIEMENGE,
    GESCHAEFTSOBJEKT,
    GESCHAEFTSPARTNER,
    MARKTLOKATION,
    MARKTTEILNEHMER,
    MESSLOKATION,
    ZAEHLER,
    KOSTEN,
    TARIF,
    PREISBLATT,
    PREISBLATTNETZNUTZUNG,
    PREISBLATTMESSUNG,
    PREISBLATTUMLAGEN,
    PREISBLATTDIENSTLEISTUNG,
    PREISBLATTKONZESSIONSABGABE,
    ZEITREIHE,
    LASTGANG,
}
@enduml
