@startuml
enum Gebiettyp {
    REGELZONE,
    MARKTGEBIET,
    BILANZIERUNGSGEBIET,
    VERTEILNETZ,
    TRANSPORTNETZ,
    REGIONALNETZ,
    AREALNETZ,
    GRUNDVERSORGUNGSGEBIET,
    VERSORGUNGSGEBIET,
}
@enduml
