@startuml
enum Geraetetyp {
    WECHSELSTROMZAEHLER,
    DREHSTROMZAEHLER,
    ZWEIRICHTUNGSZAEHLER,
    RLM_ZAEHLER,
    IMS_ZAEHLER,
    BALGENGASZAEHLER,
    MAXIMUMZAEHLER,
    MULTIPLEXANLAGE,
    PAUSCHALANLAGE,
    VERSTAERKERANLAGE,
    SUMMATIONSGERAET,
    IMPULSGEBER,
    EDL_21_ZAEHLERAUFSATZ,
    VIER_QUADRANTEN_LASTGANGZAEHLER,
    MENGENUMWERTER,
    STROMWANDLER,
    SPANNUNGSWANDLER,
    DATENLOGGER,
    KOMMUNIKATIONSANSCHLUSS,
    MODEM,
    TELEKOMMUNIKATIONSEINRICHTUNG,
    DREHKOLBENGASZAEHLER,
    TURBINENRADGASZAEHLER,
    ULTRASCHALLZAEHLER,
    WIRBELGASZAEHLER,
    MODERNE_MESSEINRICHTUNG,
    ELEKTRONISCHER_HAUSHALTSZAEHLER,
    STEUEREINRICHTUNG,
    TECHNISCHESTEUEREINRICHTUNG,
    TARIFSCHALTGERAET,
    RUNDSTEUEREMPFAENGER,
    OPTIONALE_ZUS_ZAEHLEINRICHTUNG,
    MESSWANDLERSATZ_IMS_MME,
    KOMBIMESSWANDLER_IMS_MME,
    TARIFSCHALTGERAET_IMS_MME,
    RUNDSTEUEREMPFAENGER_IMS_MME,
    TEMPERATUR_KOMPENSATION,
    HOECHSTBELASTUNGS_ANZEIGER,
    SONSTIGES_GERAET,
    SMARTMETERGATEWAY,
    STEUERBOX,
    BLOCKSTROMWANDLER,
    KOMBIMESSWANDLER,
}
@enduml
