@startuml
enum Kundentyp {
    PRIVAT,
    LANDWIRT,
    SONSTIGE,
    HAUSHALT,
    DIREKTHEIZUNG,
    GEMEINSCHAFT_MFH,
    KIRCHE,
    KWK,
    LADESAEULE,
    BELEUCHTUNG_OEFFENTLICH,
    BELEUCHTUNG_STRASSE,
    SPEICHERHEIZUNG,
    UNTERBR_EINRICHTUNG,
    WAERMEPUMPE,
}
@enduml
