@startuml
enum Leistungstyp {
    ARBEITSPREIS_WIRKARBEIT,
    LEISTUNGSPREIS_WIRKLEISTUNG,
    ARBEITSPREIS_BLINDARBEIT_IND,
    ARBEITSPREIS_BLINDARBEIT_KAP,
    GRUNDPREIS,
    MEHRMINDERMENGE,
    MESSSTELLENBETRIEB,
    MESSDIENSTLEISTUNG,
    MESSDIENSTLEISTUNG_INKL_MESSUNG,
    ABRECHNUNG,
    KONZESSIONS_ABGABE,
    KWK_UMLAGE,
    OFFSHORE_UMLAGE,
    ABLAV_UMLAGE,
    REGELENERGIE_UMLAGE,
    BILANZIERUNG_UMLAGE,
    AUSLESUNG_ZUSAETZLICH,
    ABLESUNG_ZUSAETZLICH,
    ABRECHNUNG_ZUSAETZLICH,
    SPERRUNG,
    ENTSPERRUNG,
    MAHNKOSTEN,
    INKASSOKOSTEN,
}
@enduml
