@startuml
enum NNRechnungstyp {
    ABSCHLAGSRECHNUNG,
    TURNUSRECHNUNG,
    MONATSRECHNUNG,
    WIMRECHNUNG,
    ZWISCHENRECHNUNG,
    INTEGRIERTE_13TE_RECHNUNG,
    _13TE_RECHNUNG,
    MEHRMINDERMENGENRECHNUNG,
}
@enduml
