@startuml
enum Preistyp {
    ARBEITSPREIS_EINTARIF,
    ARBEITSPREIS_HT,
    ARBEITSPREIS_NT,
    LEISTUNGSPREIS,
    MESSPREIS,
    ENTGELT_ABLESUNG,
    ENTGELT_ABRECHNUNG,
    ENTGELT_MSB,
    PROVISION,
}
@enduml
