@startuml
enum Rechnungstyp {
    ABSCHLAGSRECHNUNG,
    TURNUSRECHNUNG,
    MONATSRECHNUNG,
    WIMRECHNUNG,
    ZWISCHENRECHNUNG,
    INTEGRIERTE_13TE_RECHNUNG,
    ZUSAETZLICHE_13TE_RECHNUNG,
    MEHRMINDERMENGENRECHNUNG,
}
@enduml
