@startuml
enum Regionskriteriumtyp {
    BUNDESLANDKENNZIFFER,
    BUNDESLAND_NAME,
    MARKTGEBIET_NUMMER,
    MARKTGEBIET_NAME,
    REGELGEBIET_NUMMER,
    REGELGEBIET_NAME,
    NETZBETREIBER_NUMMER,
    NETZBETREIBER_NAME,
    BILANZIERUNGS_GEBIET_NUMMER,
    MSB_NUMMER,
    MSB_NAME,
    VERSORGER_NUMMER,
    VERSORGER_NAME,
    GRUNDVERSORGER_NUMMER,
    GRUNDVERSORGER_NAME,
    KREIS_NAME,
    KREISKENNZIFFER,
    GEMEINDE_NAME,
    GEMEINDEKENNZIFFER,
    POSTLEITZAHL,
    ORT,
    EINWOHNERZAHL_GEMEINDE,
    EINWOHNERZAHL_ORT,
    KM_UMKREIS,
    BUNDESWEIT,
}
@enduml
