@startuml
enum Zaehlertyp {
    DREHSTROMZAEHLER,
    BALGENGASZAEHLER,
    DREHKOLBENZAEHLER,
    SMARTMETER,
    LEISTUNGSZAEHLER,
    MAXIMUMZAEHLER,
    TURBINENRADGASZAEHLER,
    ULTRASCHALLGASZAEHLER,
    WECHSELSTROMZAEHLER,
}
@enduml
