@startuml
class PreisblattDienstleistung {
    + Geraetedetails : Bilanzierungsmethode? <<get>> <<set>>
}
Preisblatt <|-- PreisblattDienstleistung
PreisblattDienstleistung --> "Dienstleistungsdetails" Dienstleistungstyp
PreisblattDienstleistung --> "Herausgeber" Marktteilnehmer
@enduml
