@startuml
class PreisblattKonzessionsabgabe {
}
Preisblatt <|-- PreisblattKonzessionsabgabe
PreisblattKonzessionsabgabe --> "sparte" Sparte
PreisblattKonzessionsabgabe --> "KundengruppeKA" KundengruppeKA
@enduml
