namespace BO4E.ENUM;

public enum Unternehmensart
{
    LIEFERANT,
    NETZBETREIBER,
    MESSSTELLENBETREIBER,
    ÜBERTRAGUNGSNETZBETREIBER,
    BILANZKOORDINATOR,
    BILANZKREISVERANTWORTLICHER,
    ENERGIESERVICEANBIETER,
}
