@startuml
class GenericStringStringInfo {
    + KeyColumn : string <<get>> <<set>>
    + Value : string <<get>> <<set>>
    + ToKeyValuePair() : KeyValuePair<string, string>
}
COM <|-- GenericStringStringInfo
@enduml
