@startuml
class Notiz {
    + Autor : string <<get>> <<set>>
    + Inhalt : string <<get>> <<set>>
    + CleanUpSapNotes(context:StreamingContext) : void
}
COM <|-- Notiz
Notiz --> "Zeitpunkt" DateTime
@enduml
