@startuml
class Preisgarantie {
    + Beschreibung : string <<get>> <<set>>
}
COM <|-- Preisgarantie
Preisgarantie --> "Preisgarantietyp" Preisgarantietyp
Preisgarantie --> "ZeitlicheGueltigkeit" Zeitraum
@enduml
