@startuml
class RegionaleGueltigkeit {
}
class "List`1"<T> {
}
COM <|-- RegionaleGueltigkeit
RegionaleGueltigkeit --> "Gueltigkeitstyp" Gueltigkeitstyp
RegionaleGueltigkeit --> "KriteriumsWerte<KriteriumsWert>" "List`1"
@enduml
