name: Dependabot auto-approve / -merge
on: pull_request

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Verify commit signature.
        run: |
          curl -s https://github.com/web-flow.gpg | gpg --import
          echo "Imported GitHub keys."
          
          echo "Verifying signature of commit: $GITHUB_SHA"
          git verify-commit "$GITHUB_SHA"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
